apiVersion: apps/v1
kind: Deployment

metadata:
  name: worker

spec:
  replicas: 1

  selector:
    matchLabels:
      app: worker

  template:
    metadata:
      labels:
        app: worker

    spec:
      containers:
        - name: worker

          image: shashikarandev/taskflow-worker:latest

          env:
            - name: REDIS_HOST
              value: redis

            - name: POSTGRES_HOST
              value: postgres

            - name: POSTGRES_DB
              value: tasksdb

            - name: POSTGRES_USER
              value: postgres

            - name: POSTGRES_PASSWORD
              value: postgres

          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"

            limits:
              cpu: "100m"
              memory: "128Mi"