name: Deploy to EKS

on:
  push:
    branches:
      - main

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build API Image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/taskflow-api:latest ./api-service

      - name: Push API Image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/taskflow-api:latest

      - name: Build Worker Image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/taskflow-worker:latest ./worker

      - name: Push Worker Image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/taskflow-worker:latest

      - name: Build Frontend Image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/taskflow-frontend:latest ./frontend

      - name: Push Frontend Image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/taskflow-frontend:latest

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig --region ap-south-1 --name taskflow-eks-cluster

      - name: Deploy using Helm
        run: |
          helm upgrade --install task-flow ./taskflow-platform